{
 "title": "JVM Overview",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "Java",
  "Application"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(jvm_info,kubernetes_namespace)"
   },
   {
    "name": "app",
    "label": "app",
    "query": "label_values(jvm_info{kubernetes_namespace=~\"$namespace\"},app)"
   },
   {
    "name": "pod_ip",
    "label": "pod_ip",
    "query": "label_values(jvm_info{kubernetes_namespace=~\"$namespace\",app=~\"$app\"},instance)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_info{kubernetes_namespace=~\"$namespace\",app=~\"$app\",instance=~\"$pod_ip.*\"},instance)"
   },
   {
    "name": "pod_name",
    "label": "pod_name",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\", pod=~\"$app.*\", pod_ip=~\"$pod_ip\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Service",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_info{kubernetes_namespace=~\"$namespace\", app=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(jvm_memory_bytes_used{kubernetes_namespace=~\"$namespace\",app=\"$app\",area=\"heap\"})*100) / sum(jvm_memory_bytes_max{kubernetes_namespace=~\"$namespace\",app=\"$app\",area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 0 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{kubernetes_namespace=~\"$namespace\",app=\"$app\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{kubernetes_namespace=~\"$namespace\",app=\"$app\"})"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jvm_info{kubernetes_namespace=~\"$namespace\", app=~\"$app\"}"
    }
   ]
  },
  { "title": "Pod Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod_name=~\"$pod_name\",container_name=~\"$app\"}) by (pod_name)",
     "legendFormat": "User: {{pod_name}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\",pod=~\"$pod_name\",container=~\"$app\"}) by (pod)",
     "legendFormat": "Sys: {{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\",pod=~\"$pod_name\",container=~\"$app\"}) by (pod)",
     "legendFormat": "Total: {{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", container_name!=\"POD\", pod_name=~\"$pod_name\"}) by (pod_name)",
     "legendFormat": "Current: {{ pod_name }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", name=~\"$pod_name\"}) by (pod)",
     "legendFormat": "Requested: {{ pod }}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", pod=~\"$pod_name\"}) by (pod)",
     "legendFormat": "Limit: {{ pod }}"
    },
    {
     "expr": "sum(container_memory_rss{namespace=~\"$namespace\", container_name!=\"POD\", pod_name=~\"$pod_name\"}) by (pod_name)",
     "legendFormat": "RSS: {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\"}[5m])",
     "legendFormat": "TX:: {{ pod_name }}"
    },
    {
     "expr": "-rate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod_name=~\"$pod_name\"}[5m])",
     "legendFormat": "RX: {{ pod_name }}"
    }
   ]
  },
  { "title": "JMX Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",kubernetes_namespace=~\"$namespace\",app=\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Used {{ app }} {{ instance }}"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",kubernetes_namespace=~\"$namespace\",app=\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Max {{app}} {{ instance }}"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",kubernetes_namespace=~\"$namespace\",app=\"$app\",instance=~\"$instance\"}",
     "legendFormat": "Used  {{app}} {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{kubernetes_namespace=~\"$namespace\",app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "{{area}} memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "PS Eden Space",
   "type": "graph",
   "description": "새롭게 생성된 객체들이 위치\nEden Space 가 꽉 차게 되면, Scavenge GC 가 동작하여 참조되지 않은 객체들을 제거",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"PS Eden Space\",instance=~\"$instance\"}",
     "legendFormat": "Max  {{app}} {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"PS Eden Space\", instance=~\"$instance\"}",
     "legendFormat": "Used  {{app}} {{ instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"PS Eden Space\",instance=~\"$instance\"}",
     "legendFormat": "Committed  {{app}}{{instance}}"
    }
   ]
  },
  {
   "title": "PS Old Gen",
   "type": "graph",
   "description": "Tuned Space",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"PS Old Gen\",instance=~\"$instance\"}",
     "legendFormat": "Max  {{app}} {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"PS Old Gen\",instance=~\"$instance\"}",
     "legendFormat": "Used  {{app}} {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"PS Old Gen\",instance=~\"$instance\"}",
     "legendFormat": "Committed  {{app}} {{ instance }}"
    }
   ]
  },
  {
   "title": "PS Survivor Space",
   "type": "graph",
   "description": "intermediate-life 객체가 보관되는 공간",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"PS Survivor Space\",instance=~\"$instance\"}",
     "legendFormat": "Max {{app}} {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"PS Survivor Space\",instance=~\"$instance\"}",
     "legendFormat": "Used  {{app}} {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"PS Survivor Space\",instance=~\"$instance\"}",
     "legendFormat": "Committed  {{app}} {{instance}}"
    }
   ]
  },
  {
   "title": "Meta Space (M)",
   "type": "graph",
   "description": "Metaspace는 클래스 메타 데이터를 native 메모리에 저장하고 메모리가 부족할 경우 이를 자동으로 늘려줌\n(jdk7  이하의 Perm 영역)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"Metaspace\", instance=~\"$instance\"}",
     "legendFormat": "Max {{app}} : {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"Metaspace\", instance=~\"$instance\"}",
     "legendFormat": "Used {{app}} : {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"Metaspace\", instance=~\"$instance\"}",
     "legendFormat": "Committed {{app}} : {{instance}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space (CCS)",
   "type": "graph",
   "description": "기본적으로 압축 클래스 공간 + 압축 힙 (+ 약간의 오버 헤드)은 32GB를 초과 할 수 없습니다.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"Compressed Class Space\", instance=~\"$instance\"}",
     "legendFormat": "Max {{app}} : {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"Compressed Class Space\", instance=~\"$instance\"}",
     "legendFormat": "Used  {{app}} : {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"Compressed Class Space\", instance=~\"$instance\"}",
     "legendFormat": "Commit {{app}} : {{instance}}"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "description": "컴파일된 메소드의 네이티브 코드 생성을 저장하는 데 사용\n만약 코드 캐쉬 메모리를 모두 사용하게 되면, JVM 은 경고 메시지를 출력하고 “interpreted-only mode” 로 전환한다. JIT 컴파일러는 정지되고 더이상 바이트코드(bytecode)는 네이티브 코드로 컴파일 될지 않을 것이다. 따라서 애클리케이션이 동작은 계속되지만 크기의 순서에따라 점점 느려짐\n-XX:InitialCodeCacheSize and -XX:ReservedCodeCacheSize",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"Code Cache\", instance=~\"$instance\"}",
     "legendFormat": "Max {{app}} : {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"Code Cache\",instance=~\"$instance\"}",
     "legendFormat": "Used {{app}} : {{instance}}"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{kubernetes_namespace=~\"$namespace\",app=\"$app\", pool=\"Code Cache\",instance=~\"$instance\"}",
     "legendFormat": "Commit {{app}} : {{instance}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{kubernetes_namespace=~\"$namespace\",app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "JVM current threads [{{app}}.{{instance}}]"
    },
    {
     "expr": "jvm_threads_daemon{kubernetes_namespace=~\"$namespace\",app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "JVM daemon threads  [{{app}}.{{instance}}]"
    },
    {
     "expr": "jvm_threads_deadlocked{kubernetes_namespace=~\"$namespace\",app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "JVM deadlocked threads  [{{app}}.{{instance}}]"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{kubernetes_namespace=~\"$namespace\",app=~\"$app\",instance=~\"$instance\"}",
     "legendFormat": "loaded [{{app}}.{{instance}}]"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{kubernetes_namespace=~\"$namespace\",app=~\"$app\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{gc}} [{{app}}.{{instance}}]"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{kubernetes_namespace=~\"$namespace\",app=\"$app\", instance=~\"$instance\"}",
     "legendFormat": "{{gc}} [{{app}}.{{instance}}]"
    }
   ]
  }
 ]
}