apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cicd-workspace
  namespace: cicd
  labels:
    app: jenkins
spec:
  storageClassName: default
  accessModes:
    - ReadWriteOnce
    # - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi