apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cicd-workspace
  namespace: cicd
  labels:
    app: jenkins
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
    # - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi