apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-robot-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: mta-cicd
- kind: ServiceAccount
  name: jenkins-robot
  namespace: mta-cicd
- kind: ServiceAccount
  name: jenkins-robot
  namespace: mta-dev
