---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs-bot
  name: nodejs-bot
  namespace: mta-dev
  annotations:
   prometheus.io/scrape: 'true'
   prometheus.io/port: "8090"
spec:
  ports:
  - name: nodejs-bot
    port: 8080
    protocol: TCP
    targetPort: 8080
    # nodePort: 31003
  - name: nodejs-exporter
    port: 8090
    protocol: TCP
    targetPort: 8090
    # nodePort: 30003
  selector:
    app: nodejs-bot
  # type: NodePort
  type: ClusterIP
