apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-15.4.0
    component: alertmanager
    heritage: Helm
    release: prometheus
  name: prometheus-alertmanager
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      slack_api_url: https://hooks.slack.com/services/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
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#alert'
        username: 'SKCC'
        send_resolved: true
        icon_emoji: ":crocodile:"
        icon_url: '{{ template "slack.default.iconurl" . }}'
        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] 모니터링 이벤트 알림'
        text: "{{ range .Alerts }} *경고:* _{{ .Labels.alertname }}_\n*심각도:* `{{ .Labels.severity }}`\n*환경:* *SKCC Alert *\n*요약:* {{ .Annotations.summary }}\n*내용:* {{ .Annotations.description }}\n{{ end }}"
    route:
      group_wait: 10s
      receiver: slack-notifications
      repeat_interval: 30s