apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: kibana
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2022-02-25T02:55:19Z"
  generation: 1
  labels:
    app: kibana
    app.kubernetes.io/managed-by: Helm
    heritage: Helm
    release: kibana
  name: kibana-kibana
  namespace: monitoring
  resourceVersion: "326926"
  uid: b83ebb8b-1f2b-426d-8170-07b90fcbebd2
spec:
  ingressClassName: nginx
  rules:
  - host: kibana-example.local
    http:
      paths:
      - backend:
          service:
            name: kibana-kibana
            port:
              number: 5601
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 20.200.227.196
